name: "Build And Deploy"
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Node Setup
        uses: actions/setup-node@v4.0.0
      - name: Npm Install
        run: npm i
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Build Project
        run: ng build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: web-build
          path: public/
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          # Artifact name
          name: web-build
          # Destination path
          path: public/
      
  
