name: "Build And Deploy"
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Node Setup
        uses: actions/setup-node@v4.0.0
      - name: Npm Install
        run: npm i
      - name: Install Angular CLI
        run: npm i @angular/cli
      - name: Build Project
        run: ng build
  
