name: "Build And Deploy"
on:
  push:
  workflow_dispatch:

jobs:
  build:
    permissions:
      pages: write      
      # id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Node Setup
        uses: actions/setup-node@v4.0.0
      - name: Npm Install
        run: npm i
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Build Project
        run: ng build
      - name: Deploy web To GH-Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist/learn-angular/
      
  
